name: 'Build CCS 930 project'
description: 'Build CCS 930 project'
intpus:
  configurations:
    description: 'Comma-separated CCS project configurations list'
    required: true
    default: 'Debug'
runs:
  using: 'docker'
  image: 'ghcr.io/nor3blk/ccs930-cc26xx-docker:latest'
  args:
    - ${{ inputs.configurations }}
  entrypoint: 'entrypoint.sh'
