name: CCS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#env:
#  HOST: docker.pkg.github.com
#  IMAGE: docker.pkg.github.com/nor3blk/ccs930-cc26xx-docker/ccs930-cc26xx-docker:latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with docker
        uses: ./.github/actions/ccs930-build
        with:
          configurations: 'Debug'
