name: CCS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.pkg.github.com
  IMAGE: docker.pkg.github.com/nor3blk/ccs930-cc26xx-docker/ccs930-cc26xx-docker:latest

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: SSH Setting
        env:
          TOKEN: ${{ secrets.PRIVATE_MODULE_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo -e "$TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -lA ~/.ssh/
      - name: Checkout submodule
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Pull Docker image
        run: docker pull "${IMAGE}"

      - name: Build with docker
        uses: ./.github/actions/ccs930-build
        with:
          build_configs: 'Debug,Release'
